# Generated by Django 4.2.4 on 2023-09-27 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shopapp", "0007_sale"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "createdAt",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата создания"
                    ),
                ),
                (
                    "fullName",
                    models.CharField(
                        default="", max_length=128, verbose_name="Полное имя"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        default="", max_length=128, verbose_name="e-mail"
                    ),
                ),
                (
                    "phone",
                    models.PositiveIntegerField(default="", verbose_name="телефон"),
                ),
                (
                    "deliveryType",
                    models.CharField(
                        choices=[("ordinary", "ordinary"), ("express", "express")],
                        default="ordinary",
                        max_length=64,
                        verbose_name="тип доставки",
                    ),
                ),
                (
                    "paymentType",
                    models.CharField(
                        choices=[("online", "online"), ("someone", "someone")],
                        default="online",
                        max_length=64,
                        verbose_name="тип оплаты",
                    ),
                ),
                (
                    "totalCost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="сумма заказа",
                    ),
                ),
                (
                    "deliveryCost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="стоимость доставки",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="new", max_length=64, verbose_name="статус"
                    ),
                ),
                (
                    "city",
                    models.CharField(default="", max_length=128, verbose_name="город"),
                ),
                (
                    "address",
                    models.CharField(default="", max_length=256, verbose_name="адрес"),
                ),
            ],
            options={
                "verbose_name": "заказ",
                "verbose_name_plural": "заказы",
            },
        ),
        migrations.CreateModel(
            name="OrderItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField(default=0)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="cart.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="shopapp.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "продукты в заказе",
                "verbose_name_plural": "продукты в заказе",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="products",
            field=models.ManyToManyField(
                related_name="orders", through="cart.OrderItems", to="shopapp.product"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="пользователь",
            ),
        ),
    ]
