# Generated by Django 4.2.4 on 2023-09-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shopapp", "0002_product_productimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=42)),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(to="shopapp.tag"),
        ),
    ]
