# Generated by Django 4.2.4 on 2023-09-12 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shopapp", "0004_specification"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="specification",
            options={
                "verbose_name": "Характеристики",
                "verbose_name_plural": "Характеристики",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=128, verbose_name="Автор")),
                ("email", models.EmailField(max_length=128, verbose_name="e-mail")),
                ("text", models.TextField(verbose_name="Текст отзыва")),
                ("rate", models.PositiveSmallIntegerField(default=0)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="shopapp.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
            },
        ),
    ]
