# Generated by Django 4.2.4 on 2023-09-14 22:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shopapp", "0005_alter_specification_options_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(blank=True, to="shopapp.tag"),
        ),
    ]
