# Generated by Django 4.2.4 on 2023-09-17 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shopapp", "0006_alter_product_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "salePrice",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="цена со скидкой"
                    ),
                ),
                ("dateFrom", models.DateField(verbose_name="старт продаж")),
                ("dateTo", models.DateField(verbose_name="окончание продаж")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales",
                        to="shopapp.product",
                    ),
                ),
            ],
        ),
    ]
